# Marketplace changes
'area: marketplace':
  - 'app/(marketplace)/**/*'
  - 'components/marketplace/**/*'
  - 'lib/cart/**/*'

# Worlds changes
'area: worlds':
  - 'app/(worlds)/**/*'

# Authentication changes
'area: auth':
  - 'app/auth/**/*'
  - 'lib/supabase/**/*'
  - 'middleware.ts'

# Library/Vault changes
'area: library':
  - 'app/library/**/*'
  - 'lib/store/vault.ts'

# Guides/Content changes
'area: content':
  - 'app/guides/**/*'

# API changes
'area: api':
  - 'app/api/**/*'
  - 'lib/lemon-squeezy/**/*'

# UI/Components changes
'area: ui':
  - 'components/**/*'
  - 'app/globals.css'
  - 'tailwind.config.ts'

# Infrastructure changes
'area: infrastructure':
  - '.github/**/*'
  - 'netlify.toml'
  - 'next.config.ts'
  - 'tsconfig.json'

# Documentation
'documentation':
  - '**/*.md'
  - 'ai/**/*'
